# 基本 {{{
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'shemerey/vim-project'
on_cmd = ['Project']
hook_post_source = '''
  " ファイルが選択されたらウィンドウを閉じる
  let g:proj_flags = 'imtc'
  " <Leader>Pでプロジェクトをトグル開閉する
  nmap <silent> <Leader>P <Plug>ToggleProject
  " <Leader>pでデフォルトのプロジェクトを開く
  nmap <silent> <Leader>p :Project<CR>
'''
# }}}
# ファイル管理 {{{
# ファイラ
[[plugins]]
repo = 'Shougo/vimfiler.vim'
# }}}
# Unit {{{
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
depends = 'unite.vim'
#}}}
# コーディング関連 {{{
[[plugins]]
repo = 'scrooloose/syntastic.git'
on_ft = ['cs', 'javascript', 'vim']

# ctagsを使うのを楽にするやつ
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
if = 'executable("ctags")'
on_ft = ['cs', 'javascript', 'vim']

# タグリストを出すやつ
[[plugins]]
repo = 'majutsushi/tagbar'
if = 'executable("ctags")'
on_ft = ['cs', 'javascript', 'vim']

# コメントのトグル
[[plugins]]
repo = "tyru/caw.vim"
on_ft = ['cs', 'javascript', 'vim']
# }}}
# C# {{{
[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
if = 'has("python") && has("lua")'
on_ft = 'cs'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'MSBuild.exe server/OmniSharp.sln /p:Platform="Any CPU"'
  else
    let cmd = 'xbuild server/OmniSharp.sln'
  endif
  let g:dein#plugin.build = cmd
'''
# }}}
# その他 {{{
# TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
on_source = ['context_filetype.vim']
# }}}
# vim:set foldmethod=marker:
